version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install --update
      - aws --version

  pre_build:
    commands:
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
      - INSTANCE_ID="8edb573d-9b54-4780-9ef9-3951cc8dc9fb"
      - CONTACT_FLOW_NAME="greetCallerFlow"

  build:
    commands:
      - aws cloudformation deploy \
          --template-file infrastructure/template.yaml \
          --stack-name amazon-connect-cicd-stack \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
      - aws connect import-contact-flow \
          --instance-id "${INSTANCE_ID}" \
          --name "${CONTACT_FLOW_NAME}" \
          --content file://contact-flows/greetCallerFlow.json \
          --type CONTACT_FLOW
