AWSTemplateFormatVersion: '2010-09-09'
Description: Amazon Connect CI/CD Stack

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: lambda-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  GreetCallerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: greetCaller
      Handler: index.lambda_handler
      Runtime: python3.8
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
              name = event.get('Details',{}).get('Parameters',{}).get('Name','Guest')
              return {
                  'statusCode': 200,
                  'message': f'Hello, {name}! Welcome to Amazon Connect.'
             }